version: '3.8'

services:
  fullwebapi:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "7000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: gabriel05
      POSTGRES_DB: UsersDB
    ports:
      - "5432:5432"